#!/bin/bash
# msa - control script for the Mail Storage Agent.
#
# This script is Copyright (C) 2006 3D Informatica Srl.

##################################################################################################
### Configurazioni script di avvio - INIZIO
##################################################################################################

# N.B.: E' richiesto Java8 per l'esecuzione del processo
JAVA_COMMAND=/usr/bin/java

# Massima dimensione della memoria heap per MSA
MAXHEAP=-Xmx128m

MSAPID=/tmp/msa.pid

NICE_LEVEL=10

##################################################################################################
### Configurazioni script di avvio - FINE
##################################################################################################

bindir=$(readlink -f $0)
inst=${bindir%/*/*}
jl=$inst/lib

CLASSPATH="$inst/classes:$jl/*"

# file di log in cui registrare gli errori di lancio del MSA
LOG_FILE=$inst/logs/service.log

JAVA_FLAGS=""


# --- NO MORE CHANGES AFTER THIS LINE ---

getpid() {
	if [ -s $MSAPID ]; then
		REALPID=`cat $MSAPID`
	else
		REALPID=`ps -ef | grep "msa/lib"| grep -v grep | awk '{print $2}' | tr "\n" " "`
		if [ -n "$REALPID" ]; then
			echo "$REALPID" > $MSAPID
		fi
	fi
}

stop(){
	getpid
	
	if [ -n "$REALPID" ] ; then 
		echo -n "Stopping Mail Storage Agent..."
		for i in $REALPID; do
			kill $i 2> /dev/null && echo " [OK]" || echo " [FAILED]"
		done
	else
		echo  "Mail Storage Agent already stopped"
		exit 0 #LSB 4.1.0
	fi
	REALPID=""
	rm -f $MSAPID;
}

start(){
	getpid
	
	if [ -n "$REALPID" ] ; then
		echo "Mail Storage Agent already started"
		exit 0 #LSB 4.1.0
	else
		echo -n "Starting Mail Storage Agent..."
		nohup nice -n $NICE_LEVEL $JAVA_COMMAND -classpath "$CLASSPATH" $MAXHEAP ${JAVA_FLAGS} it.tredi.msa.MsaLauncher > $LOG_FILE 2>&1 &
		sleep 2
		rm -f $MSAPID
		
		getpid
		if [ -n $REALPID ]; then
			echo " [OK]"
		else
			echo " [FAILED]"
		fi
	fi
}

start_debug(){

	# Per DEBUG remoto sostituire la riga sottostante con quella attiva al momento
	#JAVA_FLAGS="${JAVA_FLAGS} -Xdebug -Xrunjdwp:transport=dt_socket,address=*:8035,server=y,suspend=y"
	
	JAVA_FLAGS="${JAVA_FLAGS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8035,server=y,suspend=y"
	start
}

status(){
	getpid

	if [ -z "$REALPID" ] && [ -e $MSAPID ] ; then
		echo -e "\rMail Storage Agent is not Running, but found pidfile!!"
		exit 1 #LSB 4.1.0
	elif [  -z "$REALPID" ] ; then
		echo -e "\rMail Storage Agent is not Running"
		exit 3 #LSB 4.1.0
	elif [ -e $MSAPID  ]; then
		echo -e "\rMail Storage Agent is Running PID [ $REALPID]"
		exit 0 #LSB 4.1.0
	else
		echo -e "\rMail Storage Agent is Running PID [ $REALPID] but found no pidfile!!"
		exit 0 #LSB 4.1.0
	fi
}


case $1
in
	start)
		start
	;;

	stop)
		stop
	;;

	status)
		status
	;;

	restart)
		stop 
		sleep 2
		start
	;;
	
	debug)
		start_debug
	;;

	*)
		echo "Usage: $0 {start|stop|status|restart|debug}"
		exit 1
	;;
esac
